<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="DESKTOP-JIJPL74" failures="1" tests="2" name="Test2" time="35.877" errors="0" timestamp="2022-04-10T22:28:02 IST">
  <testcase classname="com.crm.organization.ContactNameUsingPomClassTest" name="createContactTest" time="9.034"/>
  <testcase classname="com.crm.organization.CreateOrganizationTest" name="createOrganizationTest" time="9.947">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [true] but found [false]
at com.crm.organization.CreateOrganizationTest.createOrganizationTest(CreateOrganizationTest.java:51)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- createOrganizationTest -->
  <testcase classname="com.crm.genericUtility.BaseClass" name="@AfterSuite closeDBConnection" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite closeDBConnection -->
  <testcase classname="com.crm.genericUtility.BaseClass" name="@BeforeSuite openDatabase" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite openDatabase -->
</testsuite> <!-- Test2 -->
